package decision

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
)

// TrainedWeights holds the 9 multi-criteria scoring weights.
type TrainedWeights struct {
	WeightCPU        float64 `json:"WeightCPU"`
	WeightMemory     float64 `json:"WeightMemory"`
	WeightBenefit    float64 `json:"WeightBenefit"`
	WeightIdle       float64 `json:"WeightIdle"`
	WeightReplica    float64 `json:"WeightReplica"`
	WeightPriority   float64 `json:"WeightPriority"`
	WeightState      float64 `json:"WeightState"`
	WeightPDB        float64 `json:"WeightPDB"`
	WeightCheckpoint float64 `json:"WeightCheckpoint"`
}

// Sum returns the sum of all 9 weights.
func (w *TrainedWeights) Sum() float64 {
	return w.WeightCPU +
		w.WeightMemory +
		w.WeightBenefit +
		w.WeightIdle +
		w.WeightReplica +
		w.WeightPriority +
		w.WeightState +
		w.WeightPDB +
		w.WeightCheckpoint
}

// Validate checks that all weights are non-negative and sum to 1.0 within epsilon tolerance.
func (w *TrainedWeights) Validate() error {
	weights := []struct {
		name string
		val  float64
	}{
		{"WeightCPU", w.WeightCPU},
		{"WeightMemory", w.WeightMemory},
		{"WeightBenefit", w.WeightBenefit},
		{"WeightIdle", w.WeightIdle},
		{"WeightReplica", w.WeightReplica},
		{"WeightPriority", w.WeightPriority},
		{"WeightState", w.WeightState},
		{"WeightPDB", w.WeightPDB},
		{"WeightCheckpoint", w.WeightCheckpoint},
	}

	for _, item := range weights {
		if item.val < 0 {
			return fmt.Errorf("%s cannot be negative (got %f)", item.name, item.val)
		}
	}

	sum := w.Sum()
	if math.Abs(sum-1.0) > 0.005 {
		return fmt.Errorf("scoring weights must sum to 1.0 (got %f)", sum)
	}

	return nil
}

// TrainedWeightsArtifact represents the full JSON schema generated by ml/run_training.py.
type TrainedWeightsArtifact struct {
	Metadata map[string]interface{} `json:"metadata"`
	Weights  TrainedWeights         `json:"weights"`
}

// LoadPolicyFromWeightsFile reads a trained_weights.json file, validates the weights,
// and applies them to a new Policy based on DefaultPolicy().
func LoadPolicyFromWeightsFile(filePath string) (*Policy, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read weights file %q: %w", filePath, err)
	}

	var artifact TrainedWeightsArtifact
	if err := json.Unmarshal(data, &artifact); err != nil {
		// Attempt direct unmarshal into TrainedWeights in case of simplified JSON
		var directWeights TrainedWeights
		if directErr := json.Unmarshal(data, &directWeights); directErr == nil && directWeights.Sum() > 0 {
			artifact.Weights = directWeights
		} else {
			return nil, fmt.Errorf("failed to parse weights JSON from %q: %w", filePath, err)
		}
	}

	if err := artifact.Weights.Validate(); err != nil {
		return nil, fmt.Errorf("invalid weights in %q: %w", filePath, err)
	}

	policy := DefaultPolicy()
	policy.WeightCPU = artifact.Weights.WeightCPU
	policy.WeightMemory = artifact.Weights.WeightMemory
	policy.WeightBenefit = artifact.Weights.WeightBenefit
	policy.WeightIdle = artifact.Weights.WeightIdle
	policy.WeightReplica = artifact.Weights.WeightReplica
	policy.WeightPriority = artifact.Weights.WeightPriority
	policy.WeightState = artifact.Weights.WeightState
	policy.WeightPDB = artifact.Weights.WeightPDB
	policy.WeightCheckpoint = artifact.Weights.WeightCheckpoint

	return policy, nil
}
