apiVersion: v1
kind: Pod
metadata:
  name: heavy-idle-batch
  namespace: ecommerce
  labels:
    app: heavy-idle-batch
  annotations:
    reclaim.io/checkpointable: "true"
spec:
  schedulerName: adaptive-scheduler
  restartPolicy: Never
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
    - name: heavy-worker
      image: alpine:3.20
      command: ["/bin/sh", "-c", "exec sleep 86400"]
      resources:
        requests:
          cpu: "1800m"
          memory: "3Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
